# Copyright (c) 2017-2018 Via Technology Ltd. All Rights Reserved.
# Consult your license regarding permissions and restrictions.

# Describes a pru jupyter docker image
# Based on the base notebook image.

FROM nb-base:0.4.0

LABEL maintainer="pete.marshall@via-technology.aero"

# The base location for python files
ARG PROJECT_HOME=/pru-python

# Base dir for pru files
ARG PRU_HOME=/pru

# What kind of deployment is it: pru, int, ta, test etc
ARG DEPLOYMENT_TYPE=pru

# The name of the PEM file.  See the secrets configuration 
ARG PEM_FILE=pem-file.json

#
# End of common args
#

# The source code
ENV PROJECT_HOME ${PROJECT_HOME:-/pru-python}

ENV PYTHONPATH $PROJECT_HOME

ENV PRU_HOME ${PRU_HOME:-/pru}

# The default kind of deployment is int
ENV DEPLOYMENT_TYPE ${DEPLOYMENT_TYPE}

ENV DATA_HOME $HOME/data

ENV NOTEBOOK_HOME $HOME/notebooks

ENV LOGGER_HOME $HOME/logging

ENV UPLOAD_DIR $DATA_HOME/upload

ENV REFINED_DIR $DATA_HOME/refined

ENV MERGED_DIR $DATA_HOME/merged

ENV PRODUCTS $DATA_HOME/products

ENV BACKUPS $DATA_HOME/backups

# We need to tell the app where to read the PEM file from.
ENV PEM_FILE $PRU_HOME/certs/${PEM_FILE:-pem-file.json}

USER root

RUN mkdir $PRU_HOME \
 && mkdir $PROJECT_HOME \
 && mkdir $PROJECT_HOME/pru \
 && mkdir $PROJECT_HOME/apps \
 && mkdir $PROJECT_HOME/scripts \
 && mkdir $PROJECT_HOME/tools \
 && mkdir $PROJECT_HOME/notebooks \
 && mkdir $PROJECT_HOME/config

RUN chown -R 1000:100 $PRU_HOME

# Copy directories from the python repo
COPY --chown=1000:100 pru $PROJECT_HOME/pru
COPY --chown=1000:100 apps $PROJECT_HOME/apps
COPY --chown=1000:100 scripts $PROJECT_HOME/scripts
COPY --chown=1000:100 tools $PROJECT_HOME/tools
COPY --chown=1000:100 notebooks $PROJECT_HOME/notebooks
COPY --chown=1000:100 config $PROJECT_HOME/config

# NOTE COPY --chown=1000:100 does not work, even though it's documented!!
RUN chown -R 1000:100 $PRU_HOME \
 && chown -R 1000:100 $PROJECT_HOME \
 && chmod -R ugo+x $PROJECT_HOME/apps \
 && chmod -R ugo+x $PROJECT_HOME/tools \
 && chmod 777 $PROJECT_HOME/config/notebook-config.sh

# Revert to USER jovyan, see: https://github.com/jupyter/docker-stacks/issues/188
USER $NB_UID
